<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;


class Appointment extends Model
{
    public $allow_export_all = true;

    protected $fillable = ["reply_at"];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::updating(function ($model){

            $model->reply_at = Carbon::now();
        });
    }
}
